'use client';
import { useCallback, useEffect, useMemo, useState } from 'react';
type User={id:string;name:string;role:string};
type Client={id:string;name:string;rfc?:string;phone?:string;email?:string;notes?:string;_count?:{opportunities:number}};
type Opportunity={id:string;title:string;product:string;amount:number;stage:string;kind:string;ownerId:string;clientId:string;client:{name:string;phone?:string};owner:{name:string}};
type Activity={id:string;description:string;type:string;dueAt?:string;completedAt?:string;opportunityId:string;opportunity:{title:string;client:{name:string}}};
type Report={total:number;byStage:Record<string,{count:number;amount:number}>;byKind:Record<string,number>;wonAmount:number;openAmount:number};
const stages=['NUEVO','CONTACTADO','COTIZADO','NEGOCIACION','GANADO','PERDIDO'];
const kinds=['RENOVACION','NUEVO_CLIENTE','VENTA_CRUZADA','RETENCION'];
const money=(n:number)=>new Intl.NumberFormat('es-MX',{style:'currency',currency:'MXN',maximumFractionDigits:0}).format(n);
async function api(path:string,init?:RequestInit){const r=await fetch('/api/'+path,{...init,headers:{'Content-Type':'application/json',...init?.headers},cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error||'Error de conexión');return j;}
export default function Page(){
 const [user,setUser]=useState<User|null>(null),[ready,setReady]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState('');
 const [tab,setTab]=useState('Inicio'),[clients,setClients]=useState<Client[]>([]),[ops,setOps]=useState<Opportunity[]>([]),[activities,setActivities]=useState<Activity[]>([]),[users,setUsers]=useState<User[]>([]),[report,setReport]=useState<Report|null>(null);
 const [message,setMessage]=useState(''),[busy,setBusy]=useState(false),[search,setSearch]=useState('');
 const [clientForm,setClientForm]=useState({name:'',rfc:'',phone:'',email:''});
 const [opForm,setOpForm]=useState({clientId:'',title:'',product:'',amount:'0',kind:'RENOVACION',ownerId:'',notes:''});
 const [activityForm,setActivityForm]=useState({opportunityId:'',type:'TAREA',description:'',dueAt:''});
 const refresh=useCallback(async()=>{try{const [c,o,a,u,r]=await Promise.all([api('clients'),api('opportunities'),api('activities'),api('users'),api('reports')]);setClients(c);setOps(o);setActivities(a);setUsers(u);setReport(r);}catch(e){setMessage(String(e));}},[]);
 useEffect(()=>{api('auth').then(d=>{setUser(d.user);if(d.user)refresh();}).catch(()=>{}).finally(()=>setReady(true));},[refresh]);
 const submit=async(path:string,method:string,body:unknown,after?:()=>void)=>{setBusy(true);setMessage('');try{await api(path,{method,body:JSON.stringify(body)});setMessage('Guardado correctamente');after?.();await refresh();}catch(e){setMessage(e instanceof Error?e.message:'Error');}finally{setBusy(false);}};
 const mine=(o:Opportunity)=>user?.role==='ADMIN'||user?.role==='COORDINACION'||o.ownerId===user?.id;
 const filtered=useMemo(()=>clients.filter(c=>[c.name,c.rfc,c.phone].join(' ').toLowerCase().includes(search.toLowerCase())),[clients,search]);
 if(!ready)return <main className="login card">Cargando CRM...</main>;
 if(!user)return <main className="login card"><h1>MIDA CRM 360°</h1><p className="muted">Acceso al sistema comercial</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setMessage('');try{const d=await api('auth',{method:'POST',body:JSON.stringify({email,password})});setUser(d.user);await refresh();}catch(err){setMessage(String(err));}finally{setBusy(false);}}}><label>Correo</label><input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/><label>Contraseña</label><input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/><p><button disabled={busy}>Entrar</button></p>{message&&<p className="error">{message}</p>}</form></main>;
 return <div className="app"><aside className="sidebar"><h2>MIDA CRM 360°</h2>{['Inicio','Clientes','Oportunidades','Agenda','Reportes'].map(t=><button key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);setMessage('');}}>{t}</button>)}<hr style={{opacity:.2,marginTop:24}}/><p style={{padding:10}}>{user.name}<br/><small>{user.role}</small></p><button onClick={async()=>{await api('auth',{method:'DELETE'});setUser(null);}}>Cerrar sesión</button></aside>
 <main className="main"><div className="top"><div><h1 style={{margin:'0 0 6px'}}>{tab}</h1><span className="muted">Gestión comercial y renovaciones CONTPAQi</span></div><span className="pill">{user.role}</span></div>{message&&<p className={message.includes('correctamente')?'success':'error'}>{message}</p>}
 {tab==='Inicio'&&<div className="stack"><div className="grid">{[{t:'Clientes',n:clients.length},{t:'Oportunidades abiertas',n:ops.filter(o=>!['GANADO','PERDIDO'].includes(o.stage)).length},{t:'Pendientes',n:activities.filter(a=>!a.completedAt).length},{t:'Potencial comercial',n:money(report?.openAmount||0)}].map(x=><div className="card" key={x.t}><span className="muted">{x.t}</span><div className="metric">{x.n}</div></div>)}</div><div className="card"><h3>Prioridades de seguimiento</h3>{activities.filter(a=>!a.completedAt).slice(0,8).map(a=><p key={a.id}>{a.description} — <span className="muted">{a.opportunity.client.name}</span></p>)}{!activities.length&&<p className="muted">No hay actividades registradas.</p>}</div><div className="card"><h3>Enfoque comercial</h3><p>Renovaciones, captación, retención y venta cruzada. La información de Licencias MIDA se conectará posteriormente por API de solo lectura.</p></div></div>}
 {tab==='Clientes'&&<div className="stack"><div className="card"><h3>Nuevo cliente</h3><form onSubmit={e=>{e.preventDefault();submit('clients','POST',clientForm,()=>setClientForm({name:'',rfc:'',phone:'',email:''}));}}><div className="form">{(['name','rfc','phone','email'] as const).map(k=><div key={k}><label>{({name:'Razón social',rfc:'RFC',phone:'Teléfono',email:'Correo'})[k]}</label><input required={k==='name'} type={k==='email'?'email':'text'} value={clientForm[k]} onChange={e=>setClientForm({...clientForm,[k]:e.target.value})}/></div>)}</div><p><button disabled={busy}>Registrar cliente</button></p></form></div><div className="card"><div className="row"><h3>Directorio compartido</h3><input style={{maxWidth:250}} placeholder="Buscar cliente o RFC" value={search} onChange={e=>setSearch(e.target.value)}/></div><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Cliente</th><th>RFC</th><th>Contacto</th><th>Oportunidades</th></tr></thead><tbody>{filtered.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.rfc||'—'}</td><td>{c.phone?<a className="link" target="_blank" rel="noreferrer" href={'https://wa.me/'+c.phone.replace(/\D/g,'')}>WhatsApp ↗</a>:'—'}</td><td>{c._count?.opportunities||0}</td></tr>)}</tbody></table></div></div></div>}
 {tab==='Oportunidades'&&<div className="stack"><div className="card"><h3>Crear oportunidad</h3><form onSubmit={e=>{e.preventDefault();submit('opportunities','POST',{...opForm,amount:Number(opForm.amount)},()=>setOpForm({...opForm,title:'',product:'',amount:'0',notes:''}));}}><div className="form"><div><label>Cliente</label><select required value={opForm.clientId} onChange={e=>setOpForm({...opForm,clientId:e.target.value})}><option value="">Seleccionar</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div><div><label>Oportunidad</label><input required value={opForm.title} onChange={e=>setOpForm({...opForm,title:e.target.value})}/></div><div><label>Producto</label><input required value={opForm.product} onChange={e=>setOpForm({...opForm,product:e.target.value})}/></div><div><label>Importe estimado MXN</label><input type="number" min="0" value={opForm.amount} onChange={e=>setOpForm({...opForm,amount:e.target.value})}/></div><div><label>Tipo</label><select value={opForm.kind} onChange={e=>setOpForm({...opForm,kind:e.target.value})}>{kinds.map(k=><option key={k}>{k}</option>)}</select></div>{['ADMIN','COORDINACION'].includes(user.role)&&<div><label>Responsable</label><select value={opForm.ownerId} onChange={e=>setOpForm({...opForm,ownerId:e.target.value})}><option value="">Yo</option>{users.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</select></div>}</div><p><button disabled={busy||!clients.length}>Crear oportunidad</button></p></form></div><div className="kanban">{stages.map(s=><section key={s} className="column"><div className="row"><strong>{s}</strong><span className="pill">{ops.filter(o=>o.stage===s).length}</span></div>{ops.filter(o=>o.stage===s).map(o=><article className="card" key={o.id}><strong>{o.title}</strong><p className="muted">{o.client.name}</p><p>{o.product} · {money(o.amount)}</p><p className="muted">{o.kind}<br/>Responsable: {o.owner.name}</p>{mine(o)&&<><label>Cambiar etapa</label><select value={o.stage} onChange={e=>{const stage=e.target.value;const lostReason=stage==='PERDIDO'?window.prompt('Motivo de pérdida (obligatorio)')||'':undefined;if(stage==='PERDIDO'&&!lostReason)return;submit('opportunities','PATCH',{id:o.id,stage,lostReason});}}>{stages.map(x=><option key={x}>{x}</option>)}</select></>}</article>)}</section>)}</div></div>}
 {tab==='Agenda'&&<div className="stack"><div className="card"><h3>Registrar seguimiento</h3><form onSubmit={e=>{e.preventDefault();submit('activities','POST',activityForm,()=>setActivityForm({...activityForm,description:'',dueAt:''}));}}><div className="form"><div><label>Oportunidad</label><select required value={activityForm.opportunityId} onChange={e=>setActivityForm({...activityForm,opportunityId:e.target.value})}><option value="">Seleccionar</option>{ops.filter(mine).map(o=><option key={o.id} value={o.id}>{o.client.name} — {o.title}</option>)}</select></div><div><label>Tipo</label><select value={activityForm.type} onChange={e=>setActivityForm({...activityForm,type:e.target.value})}>{['LLAMADA','WHATSAPP','CORREO','COTIZACION','TAREA','NOTA'].map(t=><option key={t}>{t}</option>)}</select></div><div><label>Próxima fecha</label><input type="datetime-local" value={activityForm.dueAt} onChange={e=>setActivityForm({...activityForm,dueAt:e.target.value})}/></div><div><label>Descripción</label><input required value={activityForm.description} onChange={e=>setActivityForm({...activityForm,description:e.target.value})}/></div></div><p><button disabled={busy}>Guardar actividad</button></p></form></div><div className="card"><h3>Actividades</h3>{activities.map(a=><div className="row" style={{padding:12,borderBottom:'1px solid #eee'}} key={a.id}><div><strong>{a.description}</strong><p className="muted">{a.opportunity.client.name} · {a.type} {a.dueAt?'· '+new Date(a.dueAt).toLocaleString('es-MX'):''}</p></div><button disabled={busy||!ops.some(o=>o.id===a.opportunityId&&mine(o))} onClick={()=>submit('activities','PATCH',{id:a.id,completed:!a.completedAt})}>{a.completedAt?'Reabrir':'Completar'}</button></div>)}{!activities.length&&<p className="muted">Sin actividades.</p>}</div></div>}
 {tab==='Reportes'&&<div className="stack"><div className="grid">{[{t:'Oportunidades',n:report?.total||0},{t:'Potencial abierto',n:money(report?.openAmount||0)},{t:'Monto ganado registrado',n:money(report?.wonAmount||0)}].map(x=><div className="card" key={x.t}><span className="muted">{x.t}</span><div className="metric">{x.n}</div></div>)}</div><div className="card"><div className="row"><h3>Resultados por etapa</h3><button onClick={()=>{const lines=['Etapa,Cantidad,Importe',...stages.map(s=>[s,report?.byStage[s]?.count||0,report?.byStage[s]?.amount||0].join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mida-crm-reporte.csv';a.click();URL.revokeObjectURL(a.href);}}>Exportar CSV</button></div><table className="table"><thead><tr><th>Etapa</th><th>Cantidad</th><th>Importe</th></tr></thead><tbody>{stages.map(s=><tr key={s}><td>{s}</td><td>{report?.byStage[s]?.count||0}</td><td>{money(report?.byStage[s]?.amount||0)}</td></tr>)}</tbody></table><p className="muted">Los montos son comerciales, no facturación ni cobros confirmados.</p></div></div>}
 </main></div>;
}